name: update & deploy action

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */6 * * *

jobs:
  updateStatus:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js version 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    - run: npm run deploy
    - run: |
        git config user.name dianait
        git config user.email dianahdezsoler@gmail.com
        git add .
        git commit -m "tutorial updated"
        git push
